# Generated by Django 4.1.7 on 2023-03-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_items_image_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='desc',
        ),
        migrations.AddField(
            model_name='orders',
            name='mesto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
