# Generated by Django 4.1.7 on 2023-03-05 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orders_desc_orders_mesto_alter_orders_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='date_last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее изменение'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Не оплачен', max_length=255, verbose_name='Статус'),
        ),
    ]
