# Generated by Django 4.1.7 on 2023-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_date_creation_orders_date_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='check_info',
            field=models.FileField(null=True, upload_to='4ek/', verbose_name='Чек'),
        ),
    ]
