# Generated by Django 4.1.7 on 2023-03-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_check_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cartloyal',
            field=models.CharField(default='', max_length=20, verbose_name='Карта лояльности'),
        ),
    ]
