# Generated by Django 4.1.7 on 2023-03-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orders_cartloyal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartloyal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartloyalid', models.CharField(default='', max_length=20, verbose_name='Карта лояльности')),
                ('procent', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cartloyal',
        ),
        migrations.AddField(
            model_name='orders',
            name='cartloyal',
            field=models.ManyToManyField(to='orders.cartloyal'),
        ),
    ]
